CREATE INDEX ON SubInd_ch1 (batch_id,subsnp_id);
CREATE INDEX ON SubInd_ch1 (submitted_ind_id,subsnp_id,gty_id);
CREATE INDEX ON SubInd_ch2 (batch_id,subsnp_id);
CREATE INDEX ON SubInd_ch2 (submitted_ind_id,subsnp_id,gty_id);
CREATE INDEX ON SubInd_ch3 (batch_id,subsnp_id);
CREATE INDEX ON SubInd_ch3 (submitted_ind_id,subsnp_id,gty_id);
CREATE INDEX ON SubInd_ch4 (batch_id,subsnp_id);
CREATE INDEX ON SubInd_ch4 (submitted_ind_id,subsnp_id,gty_id);
CREATE INDEX ON SubInd_ch5 (batch_id,subsnp_id);
CREATE INDEX ON SubInd_ch5 (submitted_ind_id,subsnp_id,gty_id);
CREATE INDEX ON SubInd_ch6 (batch_id,subsnp_id);
CREATE INDEX ON SubInd_ch6 (submitted_ind_id,subsnp_id,gty_id);
CREATE INDEX ON SubInd_ch7 (batch_id,subsnp_id);
CREATE INDEX ON SubInd_ch7 (submitted_ind_id,subsnp_id,gty_id);
CREATE INDEX ON dn_table_rowcount (build_id DESC,reserved_KB_spaceused DESC);
